webtalk_init -webtalk_dir F:/Xilinx/Projects/gif402-amorce-projet-main/s4InfoAtelier4.sim/sim_1/behav/xsim/xsim.dir/atelier4_wrapper_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Mar  3 19:59:11 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "59cdf2d8-2e0b-43f5-a389-c8be70f3e13e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1814c4d5952d4bc092476e99aecaed19" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "13th Gen Intel(R) Core(TM) i5-13600K" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3494 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.33_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5312040_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2860471313 -regid "" -xml F:/Xilinx/Projects/gif402-amorce-projet-main/s4InfoAtelier4.sim/sim_1/behav/xsim/xsim.dir/atelier4_wrapper_behav/webtalk/usage_statistics_ext_xsim.xml -html F:/Xilinx/Projects/gif402-amorce-projet-main/s4InfoAtelier4.sim/sim_1/behav/xsim/xsim.dir/atelier4_wrapper_behav/webtalk/usage_statistics_ext_xsim.html -wdm F:/Xilinx/Projects/gif402-amorce-projet-main/s4InfoAtelier4.sim/sim_1/behav/xsim/xsim.dir/atelier4_wrapper_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
